/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mk.sistema.janelas;

import javax.swing.JOptionPane;
import mk.sistema.DAO.PessoaDAO;
import mk.sistema.modelo.Pessoa;

/**
 *
 * @author Maikon
 */
public class CadastroPessoa extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPessoa
     */
    public CadastroPessoa() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de pessoa");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPCadastro = new javax.swing.JPanel();
        JTNome = new javax.swing.JTextField();
        JTSobrenome = new javax.swing.JTextField();
        JLSobrenome = new javax.swing.JLabel();
        JLNome = new javax.swing.JLabel();
        BTConfirmar = new javax.swing.JButton();
        BTLimpar = new javax.swing.JButton();
        JPBuscar = new javax.swing.JPanel();
        JLCodigo = new javax.swing.JLabel();
        JTCodigo = new javax.swing.JTextField();
        BTLimpar1 = new javax.swing.JButton();
        BTBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro"));

        JLSobrenome.setText("Sobrenome:");

        JLNome.setText("Nome:");

        BTConfirmar.setText("Confirmar");
        BTConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTConfirmarActionPerformed(evt);
            }
        });

        BTLimpar.setText("Limpar");
        BTLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPCadastroLayout = new javax.swing.GroupLayout(JPCadastro);
        JPCadastro.setLayout(JPCadastroLayout);
        JPCadastroLayout.setHorizontalGroup(
            JPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPCadastroLayout.createSequentialGroup()
                        .addComponent(JLNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTNome))
                    .addGroup(JPCadastroLayout.createSequentialGroup()
                        .addComponent(JLSobrenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTLimpar)
                .addContainerGap())
        );
        JPCadastroLayout.setVerticalGroup(
            JPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNome)
                    .addComponent(JTNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLSobrenome)
                    .addComponent(JTSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTLimpar)
                    .addComponent(BTConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));

        JLCodigo.setText("Código: ");

        BTLimpar1.setText("Limpar");
        BTLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTLimpar1ActionPerformed(evt);
            }
        });

        BTBuscar.setText("Buscar");
        BTBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPBuscarLayout = new javax.swing.GroupLayout(JPBuscar);
        JPBuscar.setLayout(JPBuscarLayout);
        JPBuscarLayout.setHorizontalGroup(
            JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBuscarLayout.createSequentialGroup()
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPBuscarLayout.createSequentialGroup()
                        .addComponent(JLCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTCodigo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPBuscarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTLimpar1)))
                .addContainerGap())
        );
        JPBuscarLayout.setVerticalGroup(
            JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLCodigo)
                    .addComponent(JTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTLimpar1)
                    .addComponent(BTBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JPCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLimparActionPerformed
        try{
            JTNome.setText(null);
            JTSobrenome.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Problema ao limpar: " + e.getMessage());
        }
    }//GEN-LAST:event_BTLimparActionPerformed

    private void BTConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTConfirmarActionPerformed
        PessoaDAO con = new PessoaDAO();
        Pessoa pessoa = new Pessoa();
        
        try{
            pessoa.setNome(JTNome.getText());
            pessoa.setSobrenome(JTSobrenome.getText());
        
            con.salvar(pessoa);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Problema ao inserir: " + e.getMessage());
        }
    }//GEN-LAST:event_BTConfirmarActionPerformed

    private void BTLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTLimpar1ActionPerformed
        try{
            JTCodigo.setText(null);
        }catch(Exception e){
            JOptionPane.showConfirmDialog(rootPane, "Problema ao limpar: " + e.getMessage());
        }
    }//GEN-LAST:event_BTLimpar1ActionPerformed

    private void BTBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBuscarActionPerformed
        PessoaDAO con = new PessoaDAO();
        
       try{
            Pessoa p = con.buscar(Long.parseLong(JTCodigo.getText()));
            JOptionPane.showMessageDialog(rootPane, "ID: " + p.getId() + "\nNome: " + p.getNome() + "\nSobrenome: " + p.getSobrenome());
       }catch(Exception e){
           JOptionPane.showMessageDialog(rootPane, "Problema ao procurar registro: " + e.getMessage());
       }
    }//GEN-LAST:event_BTBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBuscar;
    private javax.swing.JButton BTConfirmar;
    private javax.swing.JButton BTLimpar;
    private javax.swing.JButton BTLimpar1;
    private javax.swing.JLabel JLCodigo;
    private javax.swing.JLabel JLNome;
    private javax.swing.JLabel JLSobrenome;
    private javax.swing.JPanel JPBuscar;
    private javax.swing.JPanel JPCadastro;
    private javax.swing.JTextField JTCodigo;
    private javax.swing.JTextField JTNome;
    private javax.swing.JTextField JTSobrenome;
    // End of variables declaration//GEN-END:variables
}
